name: Build and upload Python Package to pypi.org

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
          verbose: true
